export const SET_LOCALE = 'SET_LOCALE';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const GET_USER_INFO_PRIVATE = 'GET_USER_INFO_PRIVATE';
export const CHECK_USER_IN_COOKIE = 'CHECK_USER_IN_COOKIE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const TOGGLE_DARK_THEME = 'TOGGLE_DARK_THEME';
export const GET_MOVIES = 'GET_MOVIES';
